// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgboH9xB4XxDoOFYO5NgyZ6TofrrclZ_s',
    appId: '1:840385413394:web:0d2a62609391ee082773cb',
    messagingSenderId: '840385413394',
    projectId: 'ebarber-2006d',
    authDomain: 'ebarber-2006d.firebaseapp.com',
    storageBucket: 'ebarber-2006d.appspot.com',
    measurementId: 'G-YMM4XKG6TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSl5tfBcK_SCS0cCdaHMsQPZpuv1dse74',
    appId: '1:840385413394:android:b4999b6556697d2e2773cb',
    messagingSenderId: '840385413394',
    projectId: 'ebarber-2006d',
    storageBucket: 'ebarber-2006d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLnJE-ezorY_-ByHArmdXAafz8ceun1H0',
    appId: '1:840385413394:ios:867f5237bb7a85e62773cb',
    messagingSenderId: '840385413394',
    projectId: 'ebarber-2006d',
    storageBucket: 'ebarber-2006d.appspot.com',
    iosClientId: '840385413394-hi9s90b61136bsvhf11hc8d659njms8h.apps.googleusercontent.com',
    iosBundleId: 'com.ebarber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLnJE-ezorY_-ByHArmdXAafz8ceun1H0',
    appId: '1:840385413394:ios:d8d137b78458b3bb2773cb',
    messagingSenderId: '840385413394',
    projectId: 'ebarber-2006d',
    storageBucket: 'ebarber-2006d.appspot.com',
    iosClientId: '840385413394-k2d53i785upfan040d8i8nuks3c37dk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebarber',
  );
}
